version: '3.8'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: wallet-app
    container_name: wallet-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: wallet-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wallet_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
